### ISSUE TITLE
Baseball? ⚾ 

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#72]
For some reason, our 👦 has been obsessed with Baseball ⚾ for the last few days. 🤷‍♂️ 
So I'm opening this issue to (a) capture it. (b) discuss what we should do (c) consider buying him a bat & ball.

# Discuss

If our child(ren) suddenly become obsessed with something they learned about from someone `else` (not their parents),
what should our reaction be? Does it depend on what it is? In this case I think a **sport** that gets them **outdoors** is a **_good_ thing**. 
But if it were something _unhealthy_ like passively consuming content on a digital device, not so much.
I don't think 👦 will be playing "league" any time soon, mostly because there isn't one in `PT` ...
But that shouldn't stop us from training his hand-eye-coordination and speed perception.

# Options

Decathlon has a "JR" baseball set: 

https://www.decathlon.pt/p/taco-de-basebol-em-madeira-crianca-ba180-conjunto-24-azul/_/R-p-328833?mc=8604661
<img width="1244" alt="image" src="https://github.com/bmhco/shared/assets/194400/1342ea54-eefe-48d7-a9c0-d43e24ef2f78">

But it's made of _wood_. It's an actual "starter" set. Not a toy. The ball is a "soft ball" but it would still hurt to get hit by one. 

There are "soft" versions if we are concerned about him hurting himself or other children:
https://www.amazon.es/-/pt/dp/B010S4FL88
<img width="1205" alt="image" src="https://github.com/bmhco/shared/assets/194400/d1c72f0c-b08a-4e73-b260-849701950697">

But my preference is always to buy the "real" one not the "toy". 
@iteles what are your thoughts?

**Comment by iteles** [comment]
100% at this stage, I think we need to get the 'toy' version, for 2 reasons:
+ This is for now, an interest based on something that he doesn't actually understand yet - he doesn't _know_ what baseball is, he just wants to figure it out - once he understands what it actually is, then we can consider real equipment
+ He's at a phase where I don't really want to give him a heavy wooden bat to pick up and swing at will because he'll want to use it for everything 😅 

There are also plenty of mitts available on Vinted if we want to give him an idea of that portion of it (very little available in Portugal because as you said, it's not really a sport here).

<img width="786" alt="image" src="https://github.com/bmhco/shared/assets/4185328/b89e2372-0149-4184-9cfd-faf5aeefa64b">


Even juniors mitts:
https://www.vinted.co.uk/items/3221735883-junior-nike-baseball-mitt
<img width="1001" alt="image" src="https://github.com/bmhco/shared/assets/4185328/89a843fe-3c54-4f36-ac39-c8e03fe3797f">


https://www.vinted.pt/items/3390813557-gant-et-balle-de-baseball-enfant
![IMG_8555](https://github.com/bmhco/shared/assets/4185328/cfbd8fda-355e-4ae0-8f93-ecaf51d07c88)

**Comment by nelsonic** [comment]
@iteles will you place the orders for the bat + ball and mit? Or should I?

**Comment by iteles** [comment]
Got the ball and mitt on Vinted, will source the bat next 👌 

But I think this one is worth going to check out and potentially buy (I like that it's wider so more surface area to contact with the ball):
https://www.decathlon.pt/p/taco-de-basebol-kipsta-ba100-big-hit-espuma-em-borracha-esponjosa/
<img width="1405" alt="image" src="https://github.com/bmhco/shared/assets/4185328/cda6c04a-783b-4da1-8115-30480b648e83">

They also have a few tees, but these are more expensive:

https://www.decathlon.pt/search?Ntt=tee+basebol
<img width="1484" alt="image" src="https://github.com/bmhco/shared/assets/4185328/01047e7b-c42d-4c32-bd9b-8914500f4705">

**Comment by iteles** [comment]
Baseball mitt has arrived and we can pick it up today.

**Comment by nelsonic** [comment]
1️⃣ has thoroughly enjoyed playing baseball these last few months. zero regrets. ❤️
