### ISSUE TITLE
Golf Putting Mat (outdoor) ⛳️ 

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#78]
Our child is *Suuuuper* into Golf right now. Despite never having stepped foot on a golf course. Talks about it *constantly*. So I’m thinking of placing a putting mat on the deck/walkway of the front garden for putting practice:

https://pt.sportsdirect.com/pga-tour-putting-mat-with-guide-ball-870855#colcode=87085515

![IMG_2257](https://github.com/bmhco/shared/assets/194400/adbb616a-dbef-4c8d-89da-d77792962950)

€24 is cheap enough and given that it’s “official” PGA tour merch I expect it to be decent quality. 💭

@iteles any objections?

**Comment by nelsonic** [comment]
The decathlon equivalent has “ball return” (a groove around the side that rolls the ball back to the start):
https://www.decathlon.co.uk/p/golf-putting-mat-with-ball-return-inesis/_/R-p-4092
![IMG_2258](https://github.com/bmhco/shared/assets/194400/2bf7a48e-3791-4c97-940c-2f384476adf5)

Don’t know that it’s worth being more than double the price … 💸💭
But if we want to maximise the number of “hits” on target then ball return makes sense.

**Comment by nelsonic** [comment]
The Amazon one is decent too:

Signstek Tapetes de Putting para golfe treino de golfe manta de golfe com função de retorno automático da bola para o escritório doméstico interior ao ar livre (3 bolas de golfe grátis) https://amzn.eu/d/hQX6yPE

![IMG_2260](https://github.com/bmhco/shared/assets/194400/6d68af58-a10f-43d1-9536-3eb9520a3750)


But the ball return is *off* the green (artificial grass) so it would run along the deck …

**Comment by iteles** [comment]
I have no objections.

But I really wouldn't bother with the ball return. I would favour a simulation of the 'real world' of golf where he has to actually go get his ball rather than this just feeling like a toy.

I would be tempted to wait until he's been to the driving range/putting green to see if the enthusiasm remains before getting this because usually when he asks me to play golf with him, he really means hockey with a tennis ball.
Note that I'm not saying this from a cost perspective but from a space and 'get all the things' perspective!

**Comment by nelsonic** [comment]
https://www.clubegolfebraga.com/pt/campo
![IMG_2297](https://github.com/bmhco/shared/assets/194400/61c4fd40-4cc6-42b0-8b2a-d9fc351a38ad)

**Comment by nelsonic** [comment]
Closing. It's been good to have it. 👍
